apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
{{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
    {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: {{ .Values.backend.name }}
    spec:
      volumes:        
        - name: backend-volume
        {{- if .Values.RWS }}
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        {{- else }}
          persistentVolumeClaim:
            claimName: {{ default "pvc-backend" .Values.backend.volumeName }}
        {{- end }}
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.images.backend.repository }}:{{ .Values.images.backend.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          volumeMounts:
            - name: backend-volume
              mountPath: /data
              subPath: geoserver/data
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            {{- range .Values.backend.environment_variables }}
            - name: {{ .key }}
              value: {{ .value }}
            {{- end }}
      initContainers:
        - name: download-data
          image: eu.gcr.io/liwo-11205260-011/cloudsync
          command: ['sh', '-c']
          args: ['if [ ! -f geoserver/data-volledig.zip ]; then mkdir geoserver; echo "download geoserver data"; gsutil cp gs://liwo-data/data-volledig.zip geoserver/data-volledig.zip; cd geoserver; unzip data-volledig.zip; fi']
          workingDir: /data
          env:
            {{- range .Values.backend.environment_variables_init }}
            - name: {{ .key }}
              value: {{ .value }}
            {{- end }}
          volumeMounts:
            - name: backend-volume
              mountPath: /data
