{{- if eq .Values.RWS false}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default "pvc-database" .Values.database.volumeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
{{- end }}
