apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ .Values.database.name }}
