apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.database.pv.name }}
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: {{ .Values.database.pv.path }}
    server: {{ .Values.database.pv.server }} 
    readOnly: false
