# Default values for LIWO.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  backend: 
    repository: deltares/liwo-services
    tag: "latest"
  database:
    repository: postgis/postgis
    tag: "9.6-2.5"
  geoserver:
    repository: oscarfonts/geoserver
    tag: "2.12.1"
  frontend:
    repository: deltares/liwo-static
    tag: "latest"
  imagePullSecrets: []
  imagePullPolicy: Always

backend:
  name: "liwo-backend"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 5000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  environment_variables:
    - key: SQLALCHEMY_DATABASE_URI
      value: 

  resources: {}

database:
  name: "liwo-database"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 5432

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  environment_variables:
    - key: POSTGRES_PASSWORD
      value:
    - key: POSTGRES_USER
      value:
    - key: POSTGRES_DB
      value:

  resources: {}

frontend:
  name: "liwo-frontend"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 80

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  environment_variables:
    - key: https_proxy
      value: webproxy.rws.nl:8080
  
  resources: {}

geoserver:
  name: "liwo-geoserver"
  podAnnotations: {}

  service:
    type: ClusterIP
    port: 8080

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}

nfs:
  path:
  server:

ingress:
  environment: rws
  host: 
  enabled: false
  annotations: {}
  # gcloud compute addresses create overstroomik-static-ip --global
  # gcloud endpoints services deploy openapi.yaml
  # kubernetes.io/ingress.global-static-ip-name: "overstroomik-static-ip"
  services:
    - name: liwo-geoserver
      path: /geoserver/
      port: 8080
    - name: liwo-backend
      path: /liwo.ws/
      port: 5000
    - name: liwo-frontend
      path: /
      port: 80
